import { beforeEach, describe, expect, test } from '@jest/globals'
import { MODES } from '../lib/config/modes.mjs'
import { toContainError, ValidationError, ValidationWarning } from '../lib/helpers/error.mjs'
import { detectDeprecatedElements, validateCodeBlocks, validateTextLikeRefs, validateIprAttribute, validateSubmissionType, validateIETFTLPBoilerplateXML } from '../lib/modules/xml.mjs'
import { detectDeprecatedElements, validateCodeBlocks, validateTextLikeRefs, validateIprAttribute, validateSubmissionType, validateIETFTLPBoilerplateXML, validateIPRAutogeneratedBoilerplate } from '../lib/modules/xml.mjs'
import { baseXMLDoc } from './fixtures/base-doc.mjs'
import { cloneDeep, set } from 'lodash-es'
import fetchMock from 'jest-fetch-mock'

fetchMock.enableMocks()

expect.extend({
  toContainError
})

describe('XML document should not use deprecated elements', () => {
  test('valid ipr value', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.t', 'test')
    await expect(detectDeprecatedElements(doc)).resolves.toHaveLength(0)
  })
  test('deprecated element at first level', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.c', 'test')
    await expect(detectDeprecatedElements(doc)).resolves.toContainError('DEPRECATED_ELEMENT', ValidationWarning)
  })
  test('deprecated element nested deep', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.front.title', 'test')
    set(doc, 'data.rfc.front.author.address.spanx', 'test')
    await expect(detectDeprecatedElements(doc)).resolves.toContainError('DEPRECATED_ELEMENT', ValidationWarning)
  })
})

describe('XML document should have a valid ipr attribute', () => {
  test('valid ipr value', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    await expect(validateIprAttribute(doc)).resolves.toHaveLength(0)
  })
  test('missing ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc', {})
    await expect(validateIprAttribute(doc)).resolves.toContainError('MISSING_IPR_ATTRIBUTE', ValidationError)
  })
  test('invalid ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    // -> Empty value
    set(doc, 'data.rfc._attr.ipr', '')
    await expect(validateIprAttribute(doc)).resolves.toContainError('INVALID_IPR_VALUE', ValidationWarning)
    // -> Invalid value
    set(doc, 'data.rfc._attr.ipr', 'test')
    await expect(validateIprAttribute(doc)).resolves.toContainError('INVALID_IPR_VALUE', ValidationWarning)
  })
})

describe('XML stream document should only use allowed ipr values', () => {
  test('valid ipr value', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc._attr.submissionType', 'IETF')
    await expect(validateIprAttribute(doc)).resolves.toHaveLength(0)
  })
  test('invalid noModificationTrust200902 ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'noModificationTrust200902')
    set(doc, 'data.rfc._attr.submissionType', 'IETF')
    await expect(validateIprAttribute(doc)).resolves.toContainError('FORBIDDEN_IPR_VALUE_FOR_STREAM', ValidationError)
  })
  test('invalid noDerivativesTrust200902 ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'noDerivativesTrust200902')
    set(doc, 'data.rfc._attr.submissionType', 'IETF')
    await expect(validateIprAttribute(doc)).resolves.toContainError('FORBIDDEN_IPR_VALUE_FOR_STREAM', ValidationError)
  })
})

describe('XML document should not contain <CODE BEGINS> tags', () => {
  test('valid sourcecode value', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.sourcecode', 'test')
    await expect(validateCodeBlocks(doc)).resolves.toHaveLength(0)
  })
  test('sourcecode with a <CODE BEGINS>', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.sourcecode', '<CODE BEGINS>test')
    await expect(validateCodeBlocks(doc)).resolves.toContainError('UNNECESSARY_CODE_BEGINS', ValidationWarning)
    await expect(validateCodeBlocks(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('UNNECESSARY_CODE_BEGINS', ValidationWarning)
    await expect(validateCodeBlocks(doc, { mode: MODES.SUBMISSION })).resolves.toHaveLength(0)
  })
  test('<CODE BEGINS> without <sourcecode> tag', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.t', '<CODE BEGINS>test')
    await expect(validateCodeBlocks(doc)).resolves.toContainError('MISSING_SOURCECODE_TAG', ValidationWarning)
    await expect(validateCodeBlocks(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('MISSING_SOURCECODE_TAG', ValidationWarning)
    await expect(validateCodeBlocks(doc, { mode: MODES.SUBMISSION })).resolves.toHaveLength(0)
  })
})

describe('XML document should not contain text document refs', () => {
  test('valid <eref> ref', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.t', 'test <eref> test')
    await expect(validateTextLikeRefs(doc)).resolves.toHaveLength(0)
  })
  test('invalid ref in [1] format', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.t', 'test [1] test')
    await expect(validateTextLikeRefs(doc)).resolves.toContainError('TEXT_DOC_REF', ValidationWarning)
    await expect(validateTextLikeRefs(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('TEXT_DOC_REF', ValidationWarning)
    await expect(validateTextLikeRefs(doc, { mode: MODES.SUBMISSION })).resolves.toHaveLength(0)
  })
  test('invalid ref in [RFC1234] format', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.t', 'test [RFC1234] test')
    await expect(validateTextLikeRefs(doc)).resolves.toContainError('TEXT_DOC_REF', ValidationWarning)
    await expect(validateTextLikeRefs(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('TEXT_DOC_REF', ValidationWarning)
    await expect(validateTextLikeRefs(doc, { mode: MODES.SUBMISSION })).resolves.toHaveLength(0)
  })
})

describe('XML document should have a valid submission type', () => {
  beforeEach(() => {
    fetch.resetMocks()
  })

  test('valid submissionType', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'filename', 'draft-ietf-beep-boop.xml')
    await expect(validateSubmissionType(doc, { offline: true })).resolves.toHaveLength(0)
  })
  test('invalid stream', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'xyz')
    set(doc, 'filename', 'draft-xyz-beep-boop.xml')
    await expect(validateSubmissionType(doc, { offline: true })).resolves.toContainError('SUBMISSION_TYPE_INVALID', ValidationError)
    await expect(validateSubmissionType(doc, { offline: true, mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('SUBMISSION_TYPE_INVALID', ValidationError)
    await expect(validateSubmissionType(doc, { offline: true, mode: MODES.SUBMISSION })).resolves.toContainError('SUBMISSION_TYPE_INVALID', ValidationError)
  })
  test('filename stream mismatch', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'filename', 'draft-iab-beep-boop.xml')
    await expect(validateSubmissionType(doc, { offline: true })).resolves.toContainError('SUBMISSION_TYPE_MISMATCH', ValidationError)
    await expect(validateSubmissionType(doc, { offline: true, mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('SUBMISSION_TYPE_MISMATCH', ValidationError)
    await expect(validateSubmissionType(doc, { offline: true, mode: MODES.SUBMISSION })).resolves.toContainError('SUBMISSION_TYPE_MISMATCH', ValidationError)
  })
  test('valid submissionType with matching online stream', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'data.rfc._attr.docName', 'draft-ietf-beep-boop')
    set(doc, 'filename', 'draft-ietf-beep-boop.xml')
    fetch.mockResponse(JSON.stringify({ stream: '/api/v1/name/streamname/ietf/' }))
    await expect(validateSubmissionType(doc)).resolves.toHaveLength(0)
  })
  test('valid submissionType with non-existent online doc', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'data.rfc._attr.docName', 'draft-ietf-beep-boop')
    set(doc, 'filename', 'draft-ietf-beep-boop.xml')
    fetch.mockResponse('Not Found', { status: 404 })
    await expect(validateSubmissionType(doc)).resolves.toHaveLength(0)
  })
  test('stream mismatch with existing online doc', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'data.rfc._attr.docName', 'draft-ietf-beep-boop')
    set(doc, 'filename', 'draft-ietf-beep-boop.xml')
    fetch.mockResponse(JSON.stringify({ stream: '/api/v1/name/streamname/iab/' }))
    await expect(validateSubmissionType(doc)).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
    await expect(validateSubmissionType(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
    await expect(validateSubmissionType(doc, { mode: MODES.SUBMISSION })).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
  })
  test('stream set while existing online doc is not set', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.submissionType', 'ietf')
    set(doc, 'data.rfc._attr.docName', 'draft-ietf-beep-boop')
    set(doc, 'filename', 'draft-ietf-beep-boop.xml')
    fetch.mockResponse(JSON.stringify({ stream: null }))
    await expect(validateSubmissionType(doc)).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
    await expect(validateSubmissionType(doc, { mode: MODES.FORGIVE_CHECKLIST })).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
    await expect(validateSubmissionType(doc, { mode: MODES.SUBMISSION })).resolves.toContainError('SUBMISSION_TYPE_UNEXPECTED', ValidationError)
  })
})

describe('Validate IETF-TLP boilerplate for XML documents', () => {
  test('Valid IETF-TLP boilerplate and ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toHaveLength(0)
  })

  test('Unnecessary boilerplate text detected', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.front.t', 'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toContainError('UNNECESSARY_BOILERPLATE_TEXT', ValidationWarning)
  })

  test('Multiple boilerplate texts detected', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.front.t', 'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79. Copyright (c) 2025 IETF Trust and the persons identified as the document authors. All rights reserved.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: 'UNNECESSARY_BOILERPLATE_TEXT' }),
        expect.objectContaining({ name: 'UNNECESSARY_BOILERPLATE_TEXT' })
      ])
    )
  })

  test('No boilerplate or ipr issues in a clean document', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc.front.t', 'This is a clean document without boilerplate.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toHaveLength(0)
  })
})

describe('Test ipr and ipr autogenerated boilerplate', () => {
  test('should report error if ipr attribute is missing', async () => {
    const doc = cloneDeep(baseXMLDoc)
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toContainEqual(
      expect.objectContaining({
        name: 'MISSING_IPR_ATTRIBUTE',
        message: 'The ipr attribute is missing from the <rfc> tag.'
      })
    )
  })

  test('should warn if ipr attribute is invalid', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'somethingInvalid')
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toContainEqual(
      expect.objectContaining({
        name: 'INVALID_IPR_VALUE'
      })
    )
  })

  test('trust200902 - correct text', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance ' +
      'with the provisions of BCP 78 and BCP 79.'
    )
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toHaveLength(0)
  })

  test('trust200902 - missing required text', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc.boilerplate', 'Some incomplete or random text')

    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toContainEqual(
      expect.objectContaining({
        name: 'MISSING_EXPECTED_BOILERPLATE'
      })
    )
  })

  test('trust200902 - has unexpected "noModification"', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance ' +
      'with the provisions of BCP 78 and BCP 79.\n\n' +
      'This document may not be modified, and derivative works of it may ' +
      'not be created, except to format it for publication...'
    )

    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toHaveLength(0)
  })

  test('noModificationTrust200902 - needs 2 texts', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'noModificationTrust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance ' +
      'with the provisions of BCP 78 and BCP 79.\n\n' +
      'This document may not be modified, and derivative works of it may ' +
      'not be created, except to format it for publication as an RFC or ' +
      'to translate it into languages other than English.'
    )
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toHaveLength(0)
  })

  test('noModificationTrust200902 - missing noModification', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'noModificationTrust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance ' +
      'with the provisions of BCP 78 and BCP 79.'
    )
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toContainEqual(
      expect.objectContaining({
        name: 'MISSING_EXPECTED_BOILERPLATE'
      })
    )
  })

  test('noDerivativesTrust200902 - has correct texts', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'noDerivativesTrust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79.\n\n' +
      'This document may not be modified, and derivative works of it may ' +
      'not be created, and it may not be published except as an ' +
      'Internet-Draft.'
    )
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toHaveLength(0)
  })

  test('pre5378Trust200902 - has correct texts', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'pre5378Trust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79.\n\n' +
      'This document may contain material from IETF Documents or IETF ' +
      'Contributions published or made publicly available before ' +
      'November 10, 2008.  The person(s) controlling the copyright in some ' +
      'of this material may not have granted the IETF Trust the right to ' +
      'allow modifications of such material outside the IETF Standards ' +
      'Process. Without obtaining an adequate license from the person(s) ' +
      'controlling the copyright in such materials, this document may not ' +
      'be modified outside the IETF Standards Process, and derivative ' +
      'works of it may not be created outside the IETF Standards Process, ' +
      'except to format it for publication as an RFC or to translate it ' +
      'into languages other than English.'
    )

    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toHaveLength(0)
  })

  test('pre5378Trust200902 - missing the pre5378 text', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'pre5378Trust200902')
    set(doc, 'data.rfc.boilerplate',
      'This Internet-Draft is submitted in full conformance ' +
      'with the provisions of BCP 78 and BCP 79.'
    )
    const result = await validateIPRAutogeneratedBoilerplate(doc)
    expect(result).toContainEqual(
      expect.objectContaining({
        name: 'MISSING_EXPECTED_BOILERPLATE'
      })
    )
  })
})

describe('Validate IETF-TLP boilerplate for XML documents', () => {
  test('Valid IETF-TLP boilerplate and ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toHaveLength(0)
  })

  test('Missing ipr attribute', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr', {})
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toContainError('MISSING_IPR_ATTRIBUTE', ValidationError)
  })

  test('Invalid ipr attribute value', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'invalidValue')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toContainError('INVALID_IPR_VALUE', ValidationWarning)
  })

  test('Unnecessary boilerplate text detected', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.front.t', 'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toContainError('UNNECESSARY_BOILERPLATE_TEXT', ValidationWarning)
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toContainError('MISSING_IPR_ATTRIBUTE', ValidationError)
  })

  test('Multiple boilerplate texts detected', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc.front.t', 'This Internet-Draft is submitted in full conformance with the provisions of BCP 78 and BCP 79. Copyright (c) 2025 IETF Trust and the persons identified as the document authors. All rights reserved.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: 'UNNECESSARY_BOILERPLATE_TEXT' }),
        expect.objectContaining({ name: 'UNNECESSARY_BOILERPLATE_TEXT' })
      ])
    )
  })

  test('No boilerplate or ipr issues in a clean document', async () => {
    const doc = cloneDeep(baseXMLDoc)
    set(doc, 'data.rfc._attr.ipr', 'trust200902')
    set(doc, 'data.rfc.front.t', 'This is a clean document without boilerplate.')
    await expect(validateIETFTLPBoilerplateXML(doc)).resolves.toHaveLength(0)
  })
})
