name: idnits3 - Report a Bug
description: Javascript-based CLI / Library
labels:
  - 'component: idnits3'
type: Bug
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: URL to example draft/RFC exhibiting the issue
      description: Either provide an URL here or attach your document to the issue. This will help the developers replicate your issue.
      placeholder: 'https://www.ietf.org/archive/id/draft/example.xml'
