name: idnits3 - Suggest a New Feature or Enhancement
description: Javascript-based CLI / Library
labels:
  - 'idnits3'
type: Feature
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
