name: idnits2 - Report a Bug
description: Legacy Shell-based CLI
labels:
  - 'idnits2'
type: Bug
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
