import { Listr } from 'listr2'
import { ALLOWED_DOMAINS_DEFAULT } from './config/externals.mjs'
import { MODES } from './config/modes.mjs'
import {
  decodeBufferToUTF8,
  validateContent,
  validateEncoding
} from './modules/raw.mjs'
import { validateDocName, validateFilename } from './modules/filename.mjs'
import { validateFQDNs } from './modules/fqdn.mjs'
import { validateIPs } from './modules/ip.mjs'
import { validate2119Keywords, validateTermsStyle } from './modules/keywords.mjs'
import {
  validateAbstractSection,
  validateAuthorSection,
  validateIANAConsiderationsSection,
  validateIntroductionSection,
  validateReferencesInText,
  validateReferencesSection,
  validateSecurityConsiderationsSection
} from './modules/sections.mjs'
import {
  validateDate,
  validateObsoleteUpdateRef,
  validateCategory,
  validateVersion
} from './modules/metadata.mjs'
import {
  detectDeprecatedElements,
  validateCodeBlocks,
  validateIETFTLPBoilerplateXML,
  validateIprAttribute,
  validateIPRAutogeneratedBoilerplate,
  validateSubmissionType,
  validateTextLikeRefs,
  validateXMLBoilerplate
} from './modules/xml.mjs'
import {
  validateLineExtraSpacing,
  validateLineLength,
  validateCopyrightNoticeSectionIsNumbered,
  validateCodeBlockLicenses,
  validateCodeComments,
  validateStatusOfThisMemoSectionIsNumbered,
  validateAbstractSectionIsNumbered,
  validateLinksInText,
  validateReferenceStyle,
  validatePKorBM,
  validateHyphenatedLineBreaks,
  validateUpdatesAndObsoletesLines
} from './modules/txt.mjs'
import {
  validateDownrefs,
  validateNormativeReferences,
  validateUnclassifiedReferences
} from './modules/downref.mjs'

export async function checkNits (raw, filename, {
  year,
  allowedDomains = ALLOWED_DOMAINS_DEFAULT,
  mode = MODES.NORMAL,
  offline = false
} = {}) {
  const ext = filename.endsWith('.xml') ? 'xml' : 'txt'
  const result = []
  let doc = null
  let data = null

  const tasks = new Listr([
    {
      title: 'Pre-parsing validations',
      task: () => new Listr([
        {
          title: 'Validating filename',
          task: async () => result.push(...(await validateFilename(filename, { mode })))
        },
        {
          title: 'Validating encoding',
          task: async () => result.push(...(await validateEncoding(raw, { mode })))
        },
        {
          title: 'Decoding UTF-8',
          task: async () => { data = await decodeBufferToUTF8(raw) }
        },
        {
          title: 'Validating content',
          task: async () => result.push(...(await validateContent(data, { mode })))
        }
      ], { concurrent: false })
    },
    {
      title: 'Parsing document',
      task: async () => {
        if (ext === 'txt') {
          const { parse } = await import('./parsers/txt.mjs')
          doc = await parse(data, filename)
        } else {
          const { parse } = await import('./parsers/xml.mjs')
          doc = await parse(data, filename)
        }
      }
    },
    {
      title: 'Common validations',
      task: () => new Listr([
        { title: 'Document name', task: async () => result.push(...await validateDocName(doc, { mode })) },
        { title: 'Abstract section', task: async () => result.push(...await validateAbstractSection(doc, { mode })) },
        { title: 'Introduction section', task: async () => result.push(...await validateIntroductionSection(doc, { mode })) },
        { title: 'Security considerations section', task: async () => result.push(...await validateSecurityConsiderationsSection(doc, { mode })) },
        { title: 'Author section(s)', task: async () => result.push(...await validateAuthorSection(doc, { mode })) },
        { title: 'References section(s)', task: async () => result.push(...await validateReferencesSection(doc, { mode })) },
        { title: 'IANA considerations section', task: async () => result.push(...await validateIANAConsiderationsSection(doc, { mode })) },
        { title: 'FQDNs', task: async () => result.push(...await validateFQDNs(doc, { mode, offline })) },
        { title: 'IPs', task: async () => result.push(...await validateIPs(doc, { mode })) },
        { title: 'Requirement Level Keywords', task: async () => result.push(...await validate2119Keywords(doc, { mode })) },
        { title: 'Terms Style', task: async () => result.push(...await validateTermsStyle(doc, { mode })) },
        { title: 'Date', task: async () => result.push(...await validateDate(doc, { mode })) },
        { title: 'Updates / Obsoletes references', task: async () => result.push(...await validateObsoleteUpdateRef(doc, { mode, offline })) },
        { title: 'Category', task: async () => result.push(...await validateCategory(doc, { mode })) },
        { title: 'Version', task: async () => result.push(...await validateVersion(doc, { mode, offline })) },
        { title: 'References in text', task: async () => result.push(...await validateReferencesInText(doc, { mode })) },
        { title: 'Downrefs', task: async () => result.push(...await validateDownrefs(doc, { mode })) },
        { title: 'Normative references', task: async () => result.push(...await validateNormativeReferences(doc, { mode })) },
        { title: 'Unclassified references', task: async () => result.push(...await validateUnclassifiedReferences(doc, { mode })) }
      ], { concurrent: true })
    },
    {
      title: 'XML-specific validations',
      enabled: () => ext === 'xml',
      task: () => new Listr([
        { title: 'Deprecated elements', task: async () => result.push(...await detectDeprecatedElements(doc, { mode })) },
        { title: 'Submission type', task: async () => result.push(...await validateSubmissionType(doc, { mode, offline })) },
        { title: 'Code blocks', task: async () => result.push(...await validateCodeBlocks(doc, { mode })) },
        { title: 'Text-like references', task: async () => result.push(...await validateTextLikeRefs(doc, { mode })) },
        { title: 'IPR attribute', task: async () => result.push(...await validateIprAttribute(doc, { mode })) },
        { title: 'XML Boilerplate', task: async () => result.push(...await validateXMLBoilerplate(doc, { mode })) },
        { title: 'IETF TLP Boilerplate', task: async () => result.push(...await validateIETFTLPBoilerplateXML(doc, { mode })) },
        { title: 'IPR Autogenerated Boilerplate', task: async () => result.push(...await validateIPRAutogeneratedBoilerplate(doc, { mode })) }
      ], { concurrent: true })
    },
    {
      title: 'TXT-specific validations',
      enabled: () => ext === 'txt',
      task: () => new Listr([
        { title: 'Line length', task: async () => result.push(...await validateLineLength(doc, { mode })) },
        { title: 'Code comments', task: async () => result.push(...await validateCodeComments(doc, { mode })) },
        { title: 'Copyright notice section', task: async () => result.push(...await validateCopyrightNoticeSectionIsNumbered(doc, { mode })) },
        { title: 'Status of this memo section', task: async () => result.push(...await validateStatusOfThisMemoSectionIsNumbered(doc, { mode })) },
        { title: 'Abstract section numbered', task: async () => result.push(...await validateAbstractSectionIsNumbered(doc, { mode })) },
        { title: 'Reference links', task: async () => result.push(...await validateLinksInText(doc, { mode })) },
        { title: 'Reference style', task: async () => result.push(...await validateReferenceStyle(doc, { mode })) },
        { title: 'PK or BM first line', task: async () => result.push(...await validatePKorBM(doc, { mode })) },
        { title: 'Hyphenated line breaks', task: async () => result.push(...await validateHyphenatedLineBreaks(doc, { mode })) },
        { title: 'Line extra spacing', task: async () => result.push(...await validateLineExtraSpacing(doc, { mode })) },
        { title: 'Code block licenses', task: async () => result.push(...await validateCodeBlockLicenses(doc, { mode })) },
        { title: 'Updates and obsoletes lines', task: async () => result.push(...await validateUpdatesAndObsoletesLines(doc, { mode })) }
      ], { concurrent: true })
    }
  ])

  await tasks.run()
  return result
}
