import { ALLOWED_DOMAINS_DEFAULT } from './config/externals.mjs'
import { MODES } from './config/modes.mjs'
import {
  decodeBufferToUTF8,
  validateContent,
  validateEncoding
} from './modules/raw.mjs'
import { validateDocName, validateFilename } from './modules/filename.mjs'
import { validateFQDNs } from './modules/fqdn.mjs'
import { validateIPs } from './modules/ip.mjs'
import { validate2119Keywords, validateTermsStyle } from './modules/keywords.mjs'
import {
  validateAbstractSection,
  validateAuthorSection,
  validateIANAConsiderationsSection,
  validateIntroductionSection,
  validateReferencesInText,
  validateReferencesSection,
  validateSecurityConsiderationsSection
} from './modules/sections.mjs'
import {
  validateDate,
  validateObsoleteUpdateRef,
  validateCategory,
  validateVersion
} from './modules/metadata.mjs'
import {
  detectDeprecatedElements,
  validateCodeBlocks,
  validateIETFTLPBoilerplateXML,
  validateIprAttribute,
  validateIPRAutogeneratedBoilerplate,
  validateSubmissionType,
  validateTextLikeRefs,
  validateXMLBoilerplate
} from './modules/xml.mjs'
import {
  validateLineExtraSpacing,
  validateLineLength,
  validateCopyrightNoticeSectionIsNumbered,
  validateCodeBlockLicenses,
  validateCodeComments,
  validateStatusOfThisMemoSectionIsNumbered,
  validateAbstractSectionIsNumbered,
  validateLinksInText,
  validateReferenceStyle,
  validatePKorBM,
  validateHyphenatedLineBreaks,
  validateCopyrightSection,
  validateUpdatesAndObsoletesLines
} from './modules/txt.mjs'
import {
  validateDownrefs,
  validateInformativeReferences,
  validateNormativeReferences,
  validateUnclassifiedReferences,
  validatePublishedDraftReferences
} from './modules/downref.mjs'

/**
 * Get a list of validations to run based on document type
 *
 * @param {String} docType Document Type
 * @returns {Array} List of validation groups
 */
export function getAllValidations (docType) {
  // -> Preparsing Validations Tasks

  const validations = [
    {
      title: 'Pre-parsing validations',
      tasks: [
        {
          title: 'Validating filename',
          task: async (ctx) => validateFilename(ctx.filename, ctx.options)
        },
        {
          title: 'Validating encoding',
          task: async (ctx) => validateEncoding(ctx.raw, ctx.options)
        },
        {
          title: 'Decoding UTF-8',
          task: async (ctx) => { ctx.data = await decodeBufferToUTF8(ctx.raw) },
          isVoid: true
        },
        {
          title: 'Validating content',
          task: async (ctx) => validateContent(ctx.data, ctx.options)
        }
      ],
      concurrent: false
    }
  ]

  // -> Document Parsing Task

  switch (docType) {
    case 'txt': {
      validations.push({
        title: 'Parsing document',
        tasks: [
          {
            title: 'Parsing TXT document',
            task: async (ctx) => {
              const { parse } = await import('./parsers/txt.mjs')
              ctx.doc = await parse(ctx.data, ctx.filename)
            },
            isVoid: true
          }
        ],
        concurrent: false
      })
      break
    }
    case 'xml': {
      validations.push({
        title: 'Parsing document',
        tasks: [
          {
            title: 'Parsing XML document',
            task: async (ctx) => {
              const { parse } = await import('./parsers/xml.mjs')
              ctx.doc = await parse(ctx.data, ctx.filename)
            },
            isVoid: true
          }
        ],
        concurrent: false
      })
      break
    }
    default: {
      throw new Error('Unsupported File Format')
    }
  }

  // -> Common Validations Tasks

  validations.push({
    title: 'Common validations',
    tasks: [
      { title: 'Document name', task: async (ctx) => validateDocName(ctx.doc, ctx.options) },
      { title: 'Abstract section', task: async (ctx) => validateAbstractSection(ctx.doc, ctx.options) },
      { title: 'Introduction section', task: async (ctx) => validateIntroductionSection(ctx.doc, ctx.options) },
      { title: 'Security considerations section', task: async (ctx) => validateSecurityConsiderationsSection(ctx.doc, ctx.options) },
      { title: 'Author section(s)', task: async (ctx) => validateAuthorSection(ctx.doc, ctx.options) },
      { title: 'References section(s)', task: async (ctx) => validateReferencesSection(ctx.doc, ctx.options) },
      { title: 'IANA considerations section', task: async (ctx) => validateIANAConsiderationsSection(ctx.doc, ctx.options) },
      { title: 'FQDNs', task: async (ctx) => validateFQDNs(ctx.doc, ctx.options) },
      { title: 'IPs', task: async (ctx) => validateIPs(ctx.doc, ctx.options) },
      { title: 'Requirement Level Keywords', task: async (ctx) => validate2119Keywords(ctx.doc, ctx.options) },
      { title: 'Terms Style', task: async (ctx) => validateTermsStyle(ctx.doc, ctx.options) },
      { title: 'Date', task: async (ctx) => validateDate(ctx.doc, ctx.options) },
      { title: 'Updates / Obsoletes references', task: async (ctx) => validateObsoleteUpdateRef(ctx.doc, ctx.options) },
      { title: 'Category', task: async (ctx) => validateCategory(ctx.doc, ctx.options) },
      { title: 'Version', task: async (ctx) => validateVersion(ctx.doc, ctx.options) },
      { title: 'References in text', task: async (ctx) => validateReferencesInText(ctx.doc, ctx.options) },
      { title: 'Downrefs', task: async (ctx) => validateDownrefs(ctx.doc, ctx.options) },
      { title: 'Normative references', task: async (ctx) => validateNormativeReferences(ctx.doc, ctx.options) },
      { title: 'Unclassified references', task: async (ctx) => validateUnclassifiedReferences(ctx.doc, ctx.options) }
    ],
    concurrent: true
  })

  // -> Document Type Specific Validations Tasks

  switch (docType) {
    case 'xml': {
      validations.push({
        title: 'XML-specific validations',
        tasks: [
          { title: 'Deprecated elements', task: async (ctx) => detectDeprecatedElements(ctx.doc, ctx.options) },
          { title: 'Submission type', task: async (ctx) => validateSubmissionType(ctx.doc, ctx.options) },
          { title: 'Code blocks', task: async (ctx) => validateCodeBlocks(ctx.doc, ctx.options) },
          { title: 'Text-like references', task: async (ctx) => validateTextLikeRefs(ctx.doc, ctx.options) },
          { title: 'IPR attribute', task: async (ctx) => validateIprAttribute(ctx.doc, ctx.options) },
          { title: 'XML Boilerplate', task: async (ctx) => validateXMLBoilerplate(ctx.doc, ctx.options) },
          { title: 'IETF TLP Boilerplate', task: async (ctx) => validateIETFTLPBoilerplateXML(ctx.doc, ctx.options) },
          { title: 'IPR Autogenerated Boilerplate', task: async (ctx) => validateIPRAutogeneratedBoilerplate(ctx.doc, ctx.options) }
        ],
        concurrent: true
      })
      break
    }
    case 'txt': {
      validations.push({
        title: 'TXT-specific validations',
        tasks: [
          { title: 'Line length', task: async (ctx) => validateLineLength(ctx.doc, ctx.options) },
          { title: 'Code comments', task: async (ctx) => validateCodeComments(ctx.doc, ctx.options) },
          { title: 'Copyright notice section', task: async (ctx) => validateCopyrightNoticeSectionIsNumbered(ctx.doc, ctx.options) },
          { title: 'Status of this memo section', task: async (ctx) => validateStatusOfThisMemoSectionIsNumbered(ctx.doc, ctx.options) },
          { title: 'Abstract section numbered', task: async (ctx) => validateAbstractSectionIsNumbered(ctx.doc, ctx.options) },
          { title: 'Reference links', task: async (ctx) => validateLinksInText(ctx.doc, ctx.options) },
          { title: 'Reference style', task: async (ctx) => validateReferenceStyle(ctx.doc, ctx.options) },
          { title: 'PK or BM first line', task: async (ctx) => validatePKorBM(ctx.doc, ctx.options) },
          { title: 'Hyphenated line breaks', task: async (ctx) => validateHyphenatedLineBreaks(ctx.doc, ctx.options) },
          { title: 'Line extra spacing', task: async (ctx) => validateLineExtraSpacing(ctx.doc, ctx.options) },
          { title: 'Code block licenses', task: async (ctx) => validateCodeBlockLicenses(ctx.doc, ctx.options) },
          { title: 'Updates and obsoletes lines', task: async (ctx) => validateUpdatesAndObsoletesLines(ctx.doc, ctx.options) },
          { title: 'Validating copyright section', task: async (ctx) => validateCopyrightSection(ctx.doc, ctx.options) },
          { title: 'Validating draft references', task: async (ctx) => validatePublishedDraftReferences(ctx.doc, ctx.options) },
          { title: 'Validating informational references', task: async (ctx) => validateInformativeReferences(ctx.doc, ctx.options) }
        ],
        concurrent: true
      })
    }
  }

  return validations
}

/**
 * Perform validations on a document
 *
 * @param {Buffer} raw Buffer of the document contents
 * @param {String} filename Filename of the document to validate
 * @param {Object} options Validation options
 * @returns {Array} Validation results
 */
export async function checkNits (raw, filename, {
  year,
  allowedDomains = ALLOWED_DOMAINS_DEFAULT,
  mode = MODES.NORMAL,
  offline = false
} = {}) {
  const ext = filename.endsWith('.xml') ? 'xml' : 'txt'
  const result = []
  const ctx = {
    raw,
    filename,
    options: {
      allowedDomains,
      mode,
      offline,
      year
    }
  }

  const validations = getAllValidations(ext)

  for (const valGroup of validations) {
    if (valGroup.concurrent) {
      const valGroupResult = await Promise.all(valGroup.tasks.map(valTask => valTask.task(ctx)))
      for (const taskResult of valGroupResult) {
        if (Array.isArray(taskResult)) {
          result.push(...taskResult)
        }
      }
    } else {
      for (const valTask of valGroup.tasks) {
        const taskResult = await valTask.task(ctx)
        if (!valTask.isVoid && Array.isArray(taskResult)) {
          result.push(...taskResult)
        }
      }
    }
  }

  return result
}
