name: Run Tests

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run lint
